"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";

type Row={
 id:string;clinicName:string;region:string;district:string;respondentRole:string;vanCompany:string;currentVanDealer:string;currentPms:string;terminalCount:number;terminalUsePeriod:string;contractType:string;contractEndDate:string;monthlyCost:string;managementFee:string;linkFee:string;salesRep:string;writerName:string;contact:string;contactWhen:string;deliveryMethod:string;fieldMemo:string;resultType:string;clientId:string;devices:string[];linkedServices:string[];inconveniences:string[];costItems:string[];contractTerms:string[];improvementItems:string[];answers:Record<string,unknown>;createdAt:string;contactName:string;contactPhone:string;visitSchedule:string;consultationNote:string;
};

const emptyRow:Row={id:"",clinicName:"",region:"",district:"",respondentRole:"",vanCompany:"",currentVanDealer:"",currentPms:"",terminalCount:0,terminalUsePeriod:"",contractType:"",contractEndDate:"",monthlyCost:"",managementFee:"",linkFee:"",salesRep:"",writerName:"",contact:"",contactWhen:"",deliveryMethod:"",fieldMemo:"",resultType:"",clientId:"",devices:[],linkedServices:[],inconveniences:[],costItems:[],contractTerms:[],improvementItems:[],answers:{},createdAt:"",contactName:"",contactPhone:"",visitSchedule:"",consultationNote:""};

export default function DashboardAdmin(){
 const [host,setHost]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[manage,setManage]=useState(false),[loggedIn,setLoggedIn]=useState(false),[id,setId]=useState("admin"),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(""),[edit,setEdit]=useState<Row|null>(null),[answersText,setAnswersText]=useState("{}");
 useEffect(()=>{setLoggedIn(sessionStorage.getItem("van_admin_logged_in")==="1");const find=()=>setHost(document.querySelector(".dashboard .dash-tools"));find();const obs=new MutationObserver(find);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[]);
 const login=async()=>{setMessage("로그인 중...");const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,password})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage((d as any).error||"로그인 실패");return}sessionStorage.setItem("van_admin_logged_in","1");setLoggedIn(true);setPassword("");setMessage("");setOpen(false)};
 const load=async()=>{setMessage("DB 불러오는 중...");const r=await fetch("/api/admin/surveys",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage((d as any).error||"DB 조회 실패");if(r.status===401){sessionStorage.removeItem("van_admin_logged_in");setLoggedIn(false)}return}setRows((d as any).rows||[]);setMessage("");setManage(true)};
 const logout=async()=>{await fetch("/api/admin/login",{method:"DELETE"}).catch(()=>null);sessionStorage.removeItem("van_admin_logged_in");setLoggedIn(false);setRows([]);setManage(false);setEdit(null)};
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>[r.clinicName,r.region,r.district,r.currentVanDealer,r.currentPms,r.salesRep,r.writerName,r.contact,r.contactName,r.contactPhone,r.fieldMemo].some(v=>String(v||"").toLowerCase().includes(q)))},[rows,query]);
 const openEdit=(row:Row)=>{setEdit(structuredClone(row));setAnswersText(JSON.stringify(row.answers||{},null,2));setMessage("")};
 const patch=(key:keyof Row,value:any)=>setEdit(v=>v?{...v,[key]:value}:v);
 const save=async()=>{if(!edit)return;let answers:Record<string,unknown>;try{answers=JSON.parse(answersText||"{}")}catch{setMessage("설문 응답(answers) JSON 형식을 확인하세요.");return}if(!confirm(`${edit.clinicName||"해당 레코드"}의 변경사항을 저장하시겠습니까?`))return;setMessage("저장 중...");const r=await fetch("/api/admin/surveys",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...edit,answers})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage((d as any).error||"수정 실패");return}setRows(prev=>prev.map(x=>x.id===edit.id?(d as any).row:x));setEdit((d as any).row);setAnswersText(JSON.stringify((d as any).row?.answers||{},null,2));setMessage("변경사항이 저장되었습니다.")};
 const remove=async(row:Row)=>{if(!confirm(`${row.clinicName||"해당 레코드"} 데이터를 삭제할까요? 이 작업은 되돌릴 수 없습니다.`))return;const r=await fetch("/api/admin/surveys",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id})});if(!r.ok){const d=await r.json().catch(()=>({}));setMessage((d as any).error||"삭제 실패");return}setRows(prev=>prev.filter(x=>x.id!==row.id));setEdit(null);setMessage("")};
 const portal=host?createPortal(<>{!loggedIn?<button onClick={()=>setOpen(true)} style={btn}>Admin</button>:<><button onClick={()=>void load()} style={btn}>DB 관리</button><button onClick={()=>void logout()} style={btn}>로그아웃</button></>}</>,host):null;
 return <>{portal}
 {open&&createPortal(<div style={overlay}><div style={modal}><h2 style={{marginTop:0}}>관리자 로그인</h2><p style={help}>관리자 ID와 비밀번호를 입력하세요.</p><input style={input} value={id} onChange={e=>setId(e.target.value)} placeholder="ID" autoCapitalize="none"/><input style={input} type="password" placeholder="비밀번호" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void login()}}/><div style={actions}><button style={primary} onClick={()=>void login()}>로그인</button><button style={btn} onClick={()=>setOpen(false)}>닫기</button></div><Msg text={message}/></div></div>,document.body)}
 {manage&&createPortal(<div style={overlay}><div style={{...modal,width:"min(1180px,96vw)",maxHeight:"92vh",overflow:"auto"}}><div style={topbar}><div><h2 style={{margin:"0 0 4px"}}>설문 DB 관리</h2><div style={help}>전체 {rows.length}건 · 목록에서 상세/수정을 눌러 전체 필드를 확인하고 수정할 수 있습니다.</div></div><div style={actions}><button style={btn} onClick={()=>void load()}>새로고침</button><button style={btn} onClick={()=>setManage(false)}>닫기</button></div></div><input style={{...input,marginTop:14}} placeholder="치과명, 지역, VAN, PMS, 영업사원, 연락처 검색" value={query} onChange={e=>setQuery(e.target.value)}/><div style={tableWrap}><table style={table}><thead><tr>{["조사일","치과명","지역","VAN","PMS","영업사원","연락처","관리"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td style={td}>{r.createdAt?.slice(0,10)||"-"}</td><td style={td}><b>{r.clinicName||"-"}</b></td><td style={td}>{[r.region,r.district].filter(Boolean).join(" ")||"-"}</td><td style={td}>{r.currentVanDealer||r.vanCompany||"-"}</td><td style={td}>{r.currentPms||"-"}</td><td style={td}>{r.salesRep||r.writerName||"-"}</td><td style={td}>{r.contactPhone||r.contact||"-"}</td><td style={{...td,minWidth:150}}><button style={smallPrimary} onClick={()=>openEdit(r)}>상세/수정</button> <button style={smallDanger} onClick={()=>void remove(r)}>삭제</button></td></tr>)}</tbody></table></div><Msg text={message}/></div></div>,document.body)}
 {edit&&createPortal(<div style={overlay}><div style={{...modal,width:"min(1080px,96vw)",maxHeight:"94vh",overflow:"auto"}}><div style={topbar}><div><h2 style={{margin:"0 0 4px"}}>레코드 상세 / 수정</h2><div style={help}>{edit.clinicName||"치과명 없음"} · 전체 DB 필드</div></div><button style={btn} onClick={()=>{setEdit(null);setMessage("")}}>닫기</button></div>
 <Section title="시스템 정보"><Grid><Field label="DB ID" value={edit.id} readOnly/><Field label="조사일시" value={edit.createdAt} readOnly/><Field label="Client ID" value={edit.clientId} onChange={v=>patch("clientId",v)}/><Field label="결과 유형" value={edit.resultType} onChange={v=>patch("resultType",v)}/></Grid></Section>
 <Section title="기본정보"><Grid><Field label="치과명" value={edit.clinicName} onChange={v=>patch("clinicName",v)}/><Field label="지역" value={edit.region} onChange={v=>patch("region",v)}/><Field label="시·군·구" value={edit.district} onChange={v=>patch("district",v)}/><Field label="응답자 구분" value={edit.respondentRole} onChange={v=>patch("respondentRole",v)}/><Field label="작성자" value={edit.writerName} onChange={v=>patch("writerName",v)}/><Field label="영업사원" value={edit.salesRep} onChange={v=>patch("salesRep",v)}/></Grid></Section>
 <Section title="현재 VAN / 단말 환경"><Grid><Field label="VAN 회사" value={edit.vanCompany} onChange={v=>patch("vanCompany",v)}/><Field label="현재 VAN 대리점" value={edit.currentVanDealer} onChange={v=>patch("currentVanDealer",v)}/><Field label="현재 PMS" value={edit.currentPms} onChange={v=>patch("currentPms",v)}/><Field label="단말 수량" value={String(edit.terminalCount??0)} type="number" onChange={v=>patch("terminalCount",Number(v||0))}/><Field label="단말 사용기간" value={edit.terminalUsePeriod} onChange={v=>patch("terminalUsePeriod",v)}/><Field label="계약 형태" value={edit.contractType} onChange={v=>patch("contractType",v)}/><Field label="계약 만료일" value={edit.contractEndDate} onChange={v=>patch("contractEndDate",v)}/></Grid><Multi label="사용 단말" values={edit.devices} onChange={v=>patch("devices",v)}/><Multi label="연동 서비스" values={edit.linkedServices} onChange={v=>patch("linkedServices",v)}/></Section>
 <Section title="비용 정보"><Grid><Field label="사용료" value={edit.monthlyCost} onChange={v=>patch("monthlyCost",v)}/><Field label="관리비" value={edit.managementFee} onChange={v=>patch("managementFee",v)}/><Field label="연동비" value={edit.linkFee} onChange={v=>patch("linkFee",v)}/></Grid></Section>
 <Section title="설문 선택항목"><Multi label="불편사항" values={edit.inconveniences} onChange={v=>patch("inconveniences",v)}/><Multi label="비용 항목" values={edit.costItems} onChange={v=>patch("costItems",v)}/><Multi label="계약조건" values={edit.contractTerms} onChange={v=>patch("contractTerms",v)}/><Multi label="개선 희망사항" values={edit.improvementItems} onChange={v=>patch("improvementItems",v)}/></Section>
 <Section title="상담 / 현장 정보"><Grid><Field label="기존 연락처 필드" value={edit.contact} onChange={v=>patch("contact",v)}/><Field label="연락 희망 시기" value={edit.contactWhen} onChange={v=>patch("contactWhen",v)}/><Field label="제공 방법" value={edit.deliveryMethod} onChange={v=>patch("deliveryMethod",v)}/><Field label="연락처 성함" value={edit.contactName} onChange={v=>patch("contactName",v)}/><Field label="전화번호" value={edit.contactPhone} onChange={v=>patch("contactPhone",v)}/><Field label="방문 일정" value={edit.visitSchedule} onChange={v=>patch("visitSchedule",v)}/></Grid><Area label="현장 메모" value={edit.fieldMemo} onChange={v=>patch("fieldMemo",v)}/><Area label="상담 메모" value={edit.consultationNote} onChange={v=>patch("consultationNote",v)}/></Section>
 <Section title="설문 원본 answers"><div style={help}>원본 JSON까지 확인·수정할 수 있습니다. 형식을 유지해 주세요.</div><textarea style={{...input,minHeight:180,fontFamily:"monospace",fontSize:12}} value={answersText} onChange={e=>setAnswersText(e.target.value)}/></Section>
 <div style={{...actions,justifyContent:"space-between",marginTop:18}}><div><button style={primary} onClick={()=>void save()}>변경사항 저장</button> <button style={btn} onClick={()=>{setEdit(null);setMessage("")}}>취소</button></div><button style={danger} onClick={()=>void remove(edit)}>레코드 삭제</button></div><Msg text={message}/></div></div>,document.body)}
 </>;
}

function Section({title,children}:{title:string;children:React.ReactNode}){return <section style={section}><h3 style={{margin:"0 0 10px",fontSize:16}}>{title}</h3>{children}</section>}
function Grid({children}:{children:React.ReactNode}){return <div style={grid}>{children}</div>}
function Field({label,value,onChange,readOnly,type="text"}:{label:string;value:string;onChange?:(v:string)=>void;readOnly?:boolean;type?:string}){return <label style={labelStyle}><span style={labelText}>{label}</span><input style={{...input,marginTop:4,background:readOnly?"#f6f6f6":"#fff"}} type={type} value={value??""} readOnly={readOnly} onChange={e=>onChange?.(e.target.value)}/></label>}
function Area({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label style={{...labelStyle,display:"block",marginTop:10}}><span style={labelText}>{label}</span><textarea style={{...input,minHeight:76,marginTop:4}} value={value||""} onChange={e=>onChange(e.target.value)}/></label>}
function Multi({label,values,onChange}:{label:string;values:string[];onChange:(v:string[])=>void}){const [draft,setDraft]=useState("");const add=()=>{const v=draft.trim();if(v&&!values.includes(v))onChange([...values,v]);setDraft("")};return <div style={{marginTop:10}}><div style={labelText}>{label}</div><div style={chips}>{values.length?values.map(v=><span key={v} style={chip}>{v}<button aria-label={`${v} 제거`} onClick={()=>onChange(values.filter(x=>x!==v))} style={xBtn}>×</button></span>):<span style={help}>저장된 값 없음</span>}</div><div style={{display:"flex",gap:6,marginTop:6}}><input style={{...input,marginTop:0}} value={draft} placeholder="항목 추가" onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();add()}}}/><button style={btn} onClick={add}>추가</button></div></div>}
function Msg({text}:{text:string}){return text?<div style={{fontSize:12,color:"#9a4a00",marginTop:12}}>{text}</div>:null}

const btn:React.CSSProperties={border:"1px solid #ddd5d0",background:"#fff",borderRadius:9,padding:"9px 12px",fontWeight:700,color:"#333",cursor:"pointer"};
const primary:React.CSSProperties={...btn,background:"#f05a00",borderColor:"#f05a00",color:"#fff"};
const danger:React.CSSProperties={...btn,color:"#b42318",borderColor:"#f1b7b2",background:"#fff8f7"};
const smallPrimary:React.CSSProperties={...primary,padding:"6px 9px",fontSize:12};
const smallDanger:React.CSSProperties={...danger,padding:"6px 9px",fontSize:12};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #ddd5d0",borderRadius:9,padding:"10px 11px",font:"inherit",marginTop:8};
const help:React.CSSProperties={fontSize:13,color:"#69717d",margin:0,lineHeight:1.5};
const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:100,background:"rgba(0,0,0,.45)",display:"grid",placeItems:"center",padding:12};
const modal:React.CSSProperties={width:"min(520px,94vw)",background:"#fff",borderRadius:16,padding:20,boxShadow:"0 24px 60px rgba(0,0,0,.25)"};
const topbar:React.CSSProperties={display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"};
const actions:React.CSSProperties={display:"flex",gap:8,marginTop:10,alignItems:"center",flexWrap:"wrap"};
const tableWrap:React.CSSProperties={overflow:"auto",marginTop:12,border:"1px solid #e5dfdb",borderRadius:10};
const table:React.CSSProperties={borderCollapse:"collapse",width:"100%",minWidth:850,fontSize:12};
const th:React.CSSProperties={textAlign:"left",padding:"10px",background:"#faf8f7",borderBottom:"1px solid #e8e4e1",whiteSpace:"nowrap"};
const td:React.CSSProperties={padding:"9px 10px",borderBottom:"1px solid #eee9e6",whiteSpace:"nowrap",maxWidth:180,overflow:"hidden",textOverflow:"ellipsis"};
const section:React.CSSProperties={marginTop:14,padding:14,border:"1px solid #ebe5e1",borderRadius:12,background:"#fff"};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10};
const labelStyle:React.CSSProperties={display:"block",minWidth:0};
const labelText:React.CSSProperties={fontSize:12,fontWeight:700,color:"#4a4f55"};
const chips:React.CSSProperties={display:"flex",gap:6,flexWrap:"wrap",marginTop:6,minHeight:28,alignItems:"center"};
const chip:React.CSSProperties={display:"inline-flex",alignItems:"center",gap:5,padding:"5px 8px",background:"#fff4ed",border:"1px solid #ffd4bd",borderRadius:999,fontSize:12};
const xBtn:React.CSSProperties={border:0,background:"transparent",cursor:"pointer",fontSize:16,lineHeight:1,padding:0,color:"#8a3c12"};
