"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";

type Row={id:string;clinicName:string;region:string;district:string;currentVanDealer:string;currentPms:string;contractEndDate:string;monthlyCost:string;managementFee:string;linkFee:string;salesRep:string;contact:string;fieldMemo:string;createdAt:string};

export default function DashboardAdmin(){
 const [host,setHost]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[manage,setManage]=useState(false),[loggedIn,setLoggedIn]=useState(false),[id,setId]=useState("admin"),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState("");
 useEffect(()=>{setLoggedIn(sessionStorage.getItem("van_admin_logged_in")==="1");const find=()=>setHost(document.querySelector(".dashboard .dash-tools"));find();const obs=new MutationObserver(find);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[]);
 const login=async()=>{setMessage("로그인 중...");const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,password})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage((d as any).error||"로그인 실패");return}sessionStorage.setItem("van_admin_logged_in","1");setLoggedIn(true);setPassword("");setMessage("관리자 로그인 완료");setOpen(false)};
 const load=async()=>{setMessage("DB 불러오는 중...");const r=await fetch("/api/admin/surveys",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage((d as any).error||"DB 조회 실패");if(r.status===401){sessionStorage.removeItem("van_admin_logged_in");setLoggedIn(false)}return}setRows((d as any).rows||[]);setMessage("");setManage(true)};
 const logout=async()=>{await fetch("/api/admin/login",{method:"DELETE"}).catch(()=>null);sessionStorage.removeItem("van_admin_logged_in");setLoggedIn(false);setRows([]);setManage(false);setMessage("로그아웃되었습니다.")};
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>[r.clinicName,r.region,r.currentVanDealer,r.currentPms,r.salesRep,r.contact,r.fieldMemo].some(v=>String(v||"").toLowerCase().includes(q)))},[rows,query]);
 const remove=async(row:Row)=>{if(!confirm(`${row.clinicName} 데이터를 삭제할까요?`))return;const r=await fetch("/api/admin/surveys",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id})});if(!r.ok){const d=await r.json().catch(()=>({}));setMessage((d as any).error||"삭제 실패");if(r.status===401){sessionStorage.removeItem("van_admin_logged_in");setLoggedIn(false)}return}await load()};
 const portal=host?createPortal(<>{!loggedIn?<button onClick={()=>setOpen(true)} style={btn}>Admin</button>:<><button onClick={()=>void load()} style={btn}>DB 관리</button><button onClick={()=>void logout()} style={btn}>로그아웃</button></>}</>,host):null;
 return <>{portal}{open&&createPortal(<div style={overlay}><div style={modal}><h2 style={{marginTop:0}}>관리자 로그인</h2><p style={help}>관리자 ID와 비밀번호를 입력하세요.</p><input style={input} value={id} onChange={e=>setId(e.target.value)} placeholder="ID" autoCapitalize="none"/><input style={input} type="password" placeholder="비밀번호" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void login()}}/><div style={{display:"flex",gap:8,marginTop:10}}><button style={primary} onClick={()=>void login()}>로그인</button><button style={btn} onClick={()=>setOpen(false)}>닫기</button></div><div style={{fontSize:12,color:"#9a4a00",marginTop:12}}>{message}</div></div></div>,document.body)}{manage&&createPortal(<div style={overlay}><div style={{...modal,width:"min(1200px,96vw)",maxHeight:"90vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><div><h2 style={{margin:"0 0 5px"}}>설문 DB 관리</h2><div style={help}>Supabase 원본 DB · 전체 {rows.length}건</div></div><button style={btn} onClick={()=>setManage(false)}>닫기</button></div><input style={{...input,marginTop:14}} placeholder="치과명, 지역, VAN, PMS, 영업사원, 연락처 검색" value={query} onChange={e=>setQuery(e.target.value)}/><div style={{overflow:"auto",marginTop:12,border:"1px solid #e5dfdb",borderRadius:10}}><table style={{borderCollapse:"collapse",width:"100%",minWidth:1000,fontSize:12}}><thead><tr>{["치과명","지역","현재 VAN","현재 PMS","만료","사용료","관리비","연동비","영업사원","연락처","조사일","관리"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td style={td}><b>{r.clinicName}</b></td><td style={td}>{r.region}</td><td style={td}>{r.currentVanDealer||"-"}</td><td style={td}>{r.currentPms||"-"}</td><td style={td}>{r.contractEndDate||"-"}</td><td style={td}>{r.monthlyCost||"-"}</td><td style={td}>{r.managementFee||"-"}</td><td style={td}>{r.linkFee||"-"}</td><td style={td}>{r.salesRep||"-"}</td><td style={td}>{r.contact||"-"}</td><td style={td}>{r.createdAt?.slice(0,10)}</td><td style={td}><button style={{...btn,color:"#b42318"}} onClick={()=>void remove(r)}>삭제</button></td></tr>)}</tbody></table></div><div style={{fontSize:12,color:"#9a4a00",marginTop:10}}>{message}</div></div></div>,document.body)}</>;
}
const btn:React.CSSProperties={border:"1px solid #ddd5d0",background:"#fff",borderRadius:9,padding:"9px 12px",fontWeight:700,color:"#333",cursor:"pointer"};
const primary:React.CSSProperties={...btn,background:"#f05a00",borderColor:"#f05a00",color:"#fff"};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #ddd5d0",borderRadius:9,padding:"10px 11px",font:"inherit",marginTop:8};
const help:React.CSSProperties={fontSize:13,color:"#69717d",margin:0,lineHeight:1.5};
const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:100,background:"rgba(0,0,0,.45)",display:"grid",placeItems:"center",padding:16};
const modal:React.CSSProperties={width:"min(520px,94vw)",background:"#fff",borderRadius:16,padding:22,boxShadow:"0 24px 60px rgba(0,0,0,.25)"};
const th:React.CSSProperties={textAlign:"left",padding:"10px",background:"#faf8f7",borderBottom:"1px solid #e8e4e1",whiteSpace:"nowrap"};
const td:React.CSSProperties={padding:"9px 10px",borderBottom:"1px solid #eee9e6",whiteSpace:"nowrap",maxWidth:190,overflow:"hidden",textOverflow:"ellipsis"};
