"use client";
import {useEffect,useMemo,useState} from "react";
import {createPortal} from "react-dom";

const SUPABASE_URL="https://euleyianbkyfnubckkjk.supabase.co";
const SUPABASE_KEY="sb_publishable_iZvZfi0XGXSbNftWOjKouA_yU6ICMKC";
type Row={id:string;clinicName:string;region:string;district:string;currentVanDealer:string;currentPms:string;contractEndDate:string;monthlyCost:string;managementFee:string;linkFee:string;salesRep:string;contact:string;fieldMemo:string;createdAt:string};

export default function DashboardAdmin(){
 const [host,setHost]=useState<HTMLElement|null>(null),[open,setOpen]=useState(false),[manage,setManage]=useState(false),[token,setToken]=useState(""),[email,setEmail]=useState("datapolicy.kr@gmail.com"),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState("");
 useEffect(()=>{setToken(localStorage.getItem("van_supabase_token")||"");const find=()=>setHost(document.querySelector(".dashboard .dash-tools"));find();const obs=new MutationObserver(find);obs.observe(document.body,{childList:true,subtree:true});return()=>obs.disconnect()},[]);
 const headers=(t=token)=>({"content-type":"application/json","x-supabase-access-token":t});
 const login=async()=>{setMessage("로그인 중...");const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_KEY,"content-type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage((d as any).msg||(d as any).error_description||"로그인 실패");return}const t=(d as any).access_token||"";localStorage.setItem("van_supabase_token",t);setToken(t);setPassword("");setMessage("관리자 로그인 완료");setOpen(false)};
 const signup=async()=>{if(password.length<8){setMessage("비밀번호는 8자 이상으로 입력하세요.");return}setMessage("계정 생성 중...");const r=await fetch(`${SUPABASE_URL}/auth/v1/signup`,{method:"POST",headers:{apikey:SUPABASE_KEY,"content-type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage((d as any).msg||(d as any).error_description||"계정 생성 실패");return}setMessage("계정 생성 요청 완료. 이메일 인증 후 로그인하세요.")};
 const load=async()=>{setMessage("DB 불러오는 중...");const r=await fetch("/api/admin/surveys",{cache:"no-store",headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok){setMessage((d as any).error||"DB 조회 실패");if(r.status===401){localStorage.removeItem("van_supabase_token");setToken("")}return}setRows((d as any).rows||[]);setMessage("");setManage(true)};
 const logout=()=>{localStorage.removeItem("van_supabase_token");setToken("");setRows([]);setManage(false);setMessage("로그아웃되었습니다.")};
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>[r.clinicName,r.region,r.currentVanDealer,r.currentPms,r.salesRep,r.contact,r.fieldMemo].some(v=>String(v||"").toLowerCase().includes(q)))},[rows,query]);
 const remove=async(row:Row)=>{if(!confirm(`${row.clinicName} 데이터를 삭제할까요?`))return;const r=await fetch("/api/admin/surveys",{method:"DELETE",headers:headers(),body:JSON.stringify({id:row.id})});if(!r.ok){const d=await r.json().catch(()=>({}));setMessage((d as any).error||"삭제 실패");return}await load()};
 const portal=host?createPortal(<>{!token?<button onClick={()=>setOpen(true)} style={btn}>관리자 로그인</button>:<><button onClick={()=>void load()} style={btn}>DB 관리</button><button onClick={logout} style={btn}>관리자 로그아웃</button></>}</>,host):null;
 return <>{portal}{open&&createPortal(<div style={overlay}><div style={modal}><h2 style={{marginTop:0}}>관리자 로그인</h2><p style={help}>허용 관리자 이메일만 DB를 조회·수정할 수 있습니다.</p><input style={input} type="email" value={email} onChange={e=>setEmail(e.target.value)}/><input style={input} type="password" placeholder="비밀번호" value={password} onChange={e=>setPassword(e.target.value)}/><div style={{display:"flex",gap:8,marginTop:10}}><button style={primary} onClick={()=>void login()}>로그인</button><button style={btn} onClick={()=>void signup()}>처음 계정 생성</button></div><div style={{fontSize:12,color:"#9a4a00",marginTop:12}}>{message}</div><button style={{...btn,marginTop:14}} onClick={()=>setOpen(false)}>닫기</button></div></div>,document.body)}{manage&&createPortal(<div style={overlay}><div style={{...modal,width:"min(1200px,96vw)",maxHeight:"90vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10}}><div><h2 style={{margin:"0 0 5px"}}>설문 DB 관리</h2><div style={help}>Supabase 원본 DB · 전체 {rows.length}건</div></div><button style={btn} onClick={()=>setManage(false)}>닫기</button></div><input style={{...input,marginTop:14}} placeholder="치과명, 지역, VAN, PMS, 영업사원, 연락처 검색" value={query} onChange={e=>setQuery(e.target.value)}/><div style={{overflow:"auto",marginTop:12,border:"1px solid #e5dfdb",borderRadius:10}}><table style={{borderCollapse:"collapse",width:"100%",minWidth:1000,fontSize:12}}><thead><tr>{["치과명","지역","현재 VAN","현재 PMS","만료","사용료","관리비","연동비","영업사원","연락처","조사일","관리"].map(h=><th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td style={td}><b>{r.clinicName}</b></td><td style={td}>{r.region}</td><td style={td}>{r.currentVanDealer||"-"}</td><td style={td}>{r.currentPms||"-"}</td><td style={td}>{r.contractEndDate||"-"}</td><td style={td}>{r.monthlyCost||"-"}</td><td style={td}>{r.managementFee||"-"}</td><td style={td}>{r.linkFee||"-"}</td><td style={td}>{r.salesRep||"-"}</td><td style={td}>{r.contact||"-"}</td><td style={td}>{r.createdAt?.slice(0,10)}</td><td style={td}><button style={{...btn,color:"#b42318"}} onClick={()=>void remove(r)}>삭제</button></td></tr>)}</tbody></table></div><div style={{fontSize:12,color:"#9a4a00",marginTop:10}}>{message}</div></div></div>,document.body)}</>;
}
const btn:React.CSSProperties={border:"1px solid #ddd5d0",background:"#fff",borderRadius:9,padding:"9px 12px",fontWeight:700,color:"#333",cursor:"pointer"};
const primary:React.CSSProperties={...btn,background:"#f05a00",borderColor:"#f05a00",color:"#fff"};
const input:React.CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #ddd5d0",borderRadius:9,padding:"10px 11px",font:"inherit",marginTop:8};
const help:React.CSSProperties={fontSize:13,color:"#69717d",margin:0,lineHeight:1.5};
const overlay:React.CSSProperties={position:"fixed",inset:0,zIndex:100,background:"rgba(0,0,0,.45)",display:"grid",placeItems:"center",padding:16};
const modal:React.CSSProperties={width:"min(520px,94vw)",background:"#fff",borderRadius:16,padding:22,boxShadow:"0 24px 60px rgba(0,0,0,.25)"};
const th:React.CSSProperties={textAlign:"left",padding:"10px",background:"#faf8f7",borderBottom:"1px solid #e8e4e1",whiteSpace:"nowrap"};
const td:React.CSSProperties={padding:"9px 10px",borderBottom:"1px solid #eee9e6",whiteSpace:"nowrap",maxWidth:190,overflow:"hidden",textOverflow:"ellipsis"};
