"use client";
import {FormEvent,useEffect,useState} from "react";
import {BarChart3,Check,ClipboardList,Download,GitCompareArrows,MapPin,Printer,RefreshCw,ShieldAlert} from "lucide-react";
import { RegionalMapChart } from "./RegionalMapChart";

type Item={label:string;image?:string};
type Target={id:number;clinicName:string;region:string;district:string;currentVanDealer:string;currentPms:string;terminalUsePeriod:string;contractType:string;contractEndDate:string;monthlyCost:string;managementFee:string;linkFee:string;deliveryMethod:string;salesRep:string;createdAt:string;devices:string[];costItems:string[];contractTerms:string[];inconveniences:string[];improvementItems:string[];contactWhen:string;fieldMemo:string};
type Summary={total:number;regions:{region:string;count:number}[];devices:{device:string;count:number}[];pains:{pain:string;count:number}[];painCount:number;improvementCount:number;complianceCount:number;expiry:{m3:number;m6:number;m12:number};expiryMonths:{month:string;count:number}[];reps:string[];targets:Target[];thisMonthCount:number;previousMonthCount:number;immediateCount:number};
const S:Summary={total:0,regions:[],devices:[],pains:[],painCount:0,improvementCount:0,complianceCount:0,expiry:{m3:0,m6:0,m12:0},expiryMonths:[],reps:[],targets:[],thisMonthCount:0,previousMonthCount:0,immediateCount:0};
const img=(n:number)=>`/options/img-${String(n).padStart(3,"0")}.png`;
const groups:{name:string;title:string;subtitle?:string;items:Item[]}[]=[
 {name:"devices",title:"현재 사용중인 결제 기기 현황",subtitle:"복수선택",items:[["단말기(유선)",4],["단말기(무선)",7],["서명패드",2],["멀티패드",3],["키오스크",1],["POS",5],["기타",6]].map(([label,n])=>({label:String(label),image:img(Number(n))}))},
 {name:"linkedServices",title:"현재 사용중인 결제 연동 서비스 현황",subtitle:"복수선택",items:[["PMS/EMR",13],["접수태블릿",10],["QR결제",12],["후불결제",11],["스마트폰",9],["기타",8]].map(([label,n])=>({label:String(label),image:img(Number(n))}))},
 {name:"inconveniences",title:"불편했던 경험",subtitle:"복수선택",items:[["문의 대응",22],["소모품",19],["고장수리",18],["긴급출동",17],["방문점검",16],["이전/설치",20],["계약조건",15],["정산/입금",14],["기타",21]].map(([label,n])=>({label:String(label),image:img(Number(n))}))},
 {name:"costItems",title:"사용 비용",subtitle:"복수선택",items:[["할부금",32],["임대료",31],["관리비",30],["연동비",29],["통신비",28],["출장비",33],["위약금 경험",27],["기타",34]].map(([label,n])=>({label:String(label),image:img(Number(n))}))},
 {name:"contractTerms",title:"VAN 계약에 따른 편익",subtitle:"복수선택",items:[{label:"없음"},...[ ["현금지원",42],["무료기기",41],["월비용면제",40],["소모품",39],["매출지원",37],["리베이트",38],["타서비스 지원",36],["기타",43] ].map(([label,n])=>({label:String(label),image:img(Number(n))}))]},
 {name:"improvementItems",title:"VAN서비스에 개선이 필요한 항목",subtitle:"복수선택",items:[["비용 절감",44],["PMS 연동",45],["취소·결제 편의",46],["방문관리",47],["문의창구",48],["소모품/AS",49],["계약조건 점검",50],["기타",51]].map(([label,n])=>({label:String(label),image:img(Number(n))}))},
];
const contractItems:[[string,number?],[string,number?],[string,number?],[string,number?],[string,number?]]=[["구매",26],["임대",23],["무상제공",24],["모름",25],["기타"]];

export default function Home(){
 const [tab,setTab]=useState<"survey"|"compare"|"dashboard">("survey"),[answers,setAnswers]=useState<Record<string,string[]>>({}),[contract,setContract]=useState(""),[summary,setSummary]=useState(S),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{const r=await fetch("/api/surveys",{cache:"no-store"});if(r.ok)setSummary(await r.json())};useEffect(()=>{void load()},[]);
 const toggle=(name:string,label:string)=>setAnswers(a=>({...a,[name]:(a[name]??[]).includes(label)?a[name].filter(x=>x!==label):[...(a[name]??[]),label]}));
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const f=new FormData(e.currentTarget),raw=Object.fromEntries(f.entries());const currentPms=[raw.currentPms,raw.pmsLinkStatus&&`연동여부 ${raw.pmsLinkStatus}`].filter(Boolean).join(" · "),currentVanDealer=[raw.currentVanDealer,raw.currentDealer&&`대리점 ${raw.currentDealer}`].filter(Boolean).join(" · "),terminalUsePeriod=raw.usePeriodUnknown?"모름":String(raw.consultationUsePeriod||raw.terminalUsePeriod||"");const r=await fetch("/api/surveys",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...raw,...answers,contractType:contract,currentPms,currentVanDealer,terminalUsePeriod})});setSaving(false);if(!r.ok){const x=await r.json().catch(()=>({}));setMessage(x.error??"저장 중 문제가 발생했습니다.");return}e.currentTarget.reset();setAnswers({});setContract("");setMessage("설문이 정상적으로 저장되었습니다.");await load();}
 const max=Math.max(1,...summary.regions.map(x=>x.count));
 return <main><header className="topbar"><div className="brand"><span className="brand-mark"><img src="/osstem-roundel-transparent.png" alt=""/></span><div><strong>카드결제서비스(VAN) 설문</strong><small>카드결제 사용 중 불편한 점을 확인합니다</small></div></div><nav><button className={tab==="survey"?"active":""} onClick={()=>setTab("survey")}><ClipboardList size={18}/>설문 입력</button><button className={tab==="compare"?"active":""} onClick={()=>{setTab("compare");void load()}}><GitCompareArrows size={18}/>비교 제안</button><button className={tab==="dashboard"?"active":""} onClick={()=>{setTab("dashboard");void load()}}><BarChart3 size={18}/>대시보드</button></nav></header>
 {tab==="survey"?<div className="page-shell survey-page"><div className="survey-heading"><div><span className="survey-logo-crop"><img src="/osstem-wordmark-transparent.png" alt="OSSTEM"/></span><h1>카드결제서비스(VAN) 설문</h1><p>“카드결제 사용중 불편한 점을 확인해서 도와드리고자 합니다.” <small>아는 항목만 체크하셔도 됩니다.</small></p></div><span className="time">약 3분 소요</span></div><form onSubmit={submit}>
  <SurveyBlock title="VAN서비스 사용 현황" numbers={[1,2]}>{groups.slice(0,2).map((g,i)=><OptionGroup key={g.name} number={i+1} group={g} selected={answers[g.name]??[]} toggle={toggle}/>)}</SurveyBlock>
  <SurveyBlock title="VAN서비스 불편 경험" numbers={[3]}><OptionGroup number={3} group={groups[2]} selected={answers.inconveniences??[]} toggle={toggle}/></SurveyBlock>
  <SurveyBlock title="VAN서비스 계약 현황" numbers={[4,5,6,7]}><div className="option-group"><QuestionTitle number={4} title="단말기 계약 형태"/><div className="option-grid compact-options">{contractItems.map(([label,n])=><button type="button" key={label} className={contract===label?"option selected":"option"} onClick={()=>setContract(label)}>{n?<img src={img(n)} alt=""/>:<span className="text-icon">···</span>}<strong>{label}</strong>{contract===label&&<Check/>}</button>)}</div></div><div className="option-group"><QuestionTitle number={5} title="단말기 사용기간"/><div className="period-options">{["1년미만","1~3년","3~5년","모름"].map(x=><label key={x}><input type="radio" name="terminalUsePeriod" value={x}/><span>{x}</span></label>)}</div></div><OptionGroup number={6} group={groups[3]} selected={answers.costItems??[]} toggle={toggle}/><OptionGroup number={7} group={groups[4]} selected={answers.contractTerms??[]} toggle={toggle}/></SurveyBlock>
  <SurveyBlock title="VAN서비스에 개선이 필요한 항목"><OptionGroup number={8} group={groups[5]} selected={answers.improvementItems??[]} toggle={toggle}/></SurveyBlock>
  <section className="survey-block consultation"><h2>상담 희망 정보</h2><div className="consultation-grid"><div className="consultation-panel consultation-left"><div className="info-row split"><label>치과명</label><input required name="clinicName"/><label>지역</label><select required name="region" defaultValue="서울">{["서울","부산","대구","인천","광주","대전","울산","세종","경기","강원","충북","충남","전북","전남","경북","경남","제주"].map(x=><option key={x}>{x}</option>)}</select></div><div className="info-row split"><label>현재 PMS</label><select name="currentPms" defaultValue="오스템"><option>오스템</option><option>타사</option><option>없음</option></select><label>연동여부</label><select name="pmsLinkStatus" defaultValue="모름"><option>네</option><option>아니오</option><option>모름</option></select></div><div className="info-row split"><label>현재 VAN사</label><input name="currentVanDealer"/><label>대리점</label><input name="currentDealer"/></div><div className="info-row memo-row"><label>현장 메모</label><textarea name="fieldMemo" placeholder="원장님 말씀, 특이사항, 경쟁사 제안 등"/></div><div className="info-row"><label>연락처(성함/전화번호)</label><input name="contact"/></div></div><div className="consultation-panel consultation-right"><div className="info-row period-row"><label>단말기 사용기간</label><input name="consultationUsePeriod"/><span className="unknown-check"><input type="checkbox" name="usePeriodUnknown" id="use-period-unknown"/><label htmlFor="use-period-unknown">모름</label></span></div><div className="info-row"><label>약정 만료일</label><input name="contractEndDate" type="month"/></div><div className="info-row cost-row"><label>사용료(할부/렌탈)</label><input name="monthlyCost" inputMode="numeric"/><b>원/월</b></div><div className="info-row cost-row"><label>관리비</label><input name="managementFee" inputMode="numeric"/><b>원/월</b></div><div className="info-row cost-row"><label>연동비</label><input name="linkFee" inputMode="numeric"/><b>원/월</b></div><div className="info-row"><label>오스템 영업사원</label><input required name="salesRep"/></div></div></div><input type="hidden" name="district" value=""/><input type="hidden" name="contactWhen" value=""/><input type="hidden" name="deliveryMethod" value=""/></section>
  <div className="submit-row"><p className={message.includes("정상")?"success":"error"}>{message}</p><button className="submit" disabled={saving}>{saving?<><RefreshCw className="spin"/>저장 중</>:"설문 제출하기"}</button></div>
 </form></div>:tab==="compare"?<Comparison targets={summary.targets}/>:<Dashboard summary={summary} max={max} refresh={load}/>}<footer>OSSTEM IMPLANT · VAN서비스 현황 조사</footer></main>
}

function SurveyBlock({title,children}:{title:string;numbers?:number[];children:React.ReactNode}){return <section className="survey-block"><h2>{title}</h2>{children}</section>}
function QuestionTitle({number,title,subtitle}:{number?:number;title:string;subtitle?:string}){return <div className="question-title">{number&&<span>{number}</span>}<strong>{title}</strong>{subtitle&&<small>({subtitle})</small>}</div>}
function OptionGroup({number,group,selected,toggle}:{number?:number;group:{name:string;title:string;subtitle?:string;items:Item[]};selected:string[];toggle:(n:string,l:string)=>void}){return <div className="option-group"><QuestionTitle number={number} title={group.title} subtitle={group.subtitle}/><div className="option-grid">{group.items.map(item=><button type="button" key={item.label} className={selected.includes(item.label)?"option selected":"option"} onClick={()=>toggle(group.name,item.label)}>{item.image?<img src={item.image} alt=""/>:<span className="none-icon">⊘</span>}<strong>{item.label}</strong>{selected.includes(item.label)&&<Check/>}</button>)}</div></div>}

const comparisonGroups=[
 {name:"사용성",items:["단말기 이용","승인 정산","PMS연동"]},
 {name:"기본비용",items:["단말기","관리비","연동비","소모품"]},
 {name:"사용조건",items:["의무사용","대응채널","내방상담","출장수리","위약금"]},
 {name:"특별지원",items:["현금지원","타서비스"]},
];
const osstemDefaults:Record<string,string>={"단말기 이용":"동일하게 제공","승인 정산":"동일하게 제공\n(정산입금 불편 시 문제없음)","PMS연동":"PMS 여부 무관","단말기":"252,000원/3년","관리비":"108,000원/3년","연동비":"0원/3년","소모품":"0원/3년","의무사용":"동일","대응채널":"전화, 영업사원, 웹 플랫폼","내방상담":"영업사원 수시방문","출장수리":"무료(임대 시)","위약금":"할부 잔금","현금지원":"-","타서비스":"-"};
const comparisonNotes:Record<string,string>={"단말기":"단말기+멀티패드 기준","연동비":"원클릭 기준","소모품":"연 1롤 사용 기준","현금지원":"기본비용 차이 확인","타서비스":"합법적 범위에서만"};
const moneyValue=(value="")=>Number((value.match(/[\d,]+/)?.[0]??"0").replaceAll(",",""))||0;
const threeYear=(value:string,fallback:number)=>`${(moneyValue(value)*36||fallback).toLocaleString("ko-KR")}원/3년`;

function Comparison({targets}:{targets:Target[]}){
 const [selected,setSelected]=useState("");
 const target=targets.find(x=>String(x.id)===selected);
 const derive=(label:string)=>{if(label==="단말기 이용")return target?.devices.join(", ")||"단말기(유선), 멀티패드";if(label==="승인 정산")return target?.inconveniences.includes("정산/입금")?"정산입금 불편":"일상업무";if(label==="PMS연동")return target?.currentPms||"없음";if(label==="단말기")return threeYear(target?.monthlyCost||"",360000);if(label==="관리비")return threeYear(target?.managementFee||"",360000);if(label==="연동비")return threeYear(target?.linkFee||"",540000);if(label==="소모품")return "90,000원/3년";if(label==="의무사용")return target?.terminalUsePeriod||"3년";if(label==="대응채널")return "전화상담";if(label==="내방상담")return "없음";if(label==="출장수리")return "유료(구매 시)";if(label==="위약금")return "기기값 2~3배";if(label==="현금지원")return target?.contractTerms.includes("현금지원")?"Y":"-";if(label==="타서비스")return target?.contractTerms.filter(x=>["무료기기","월비용면제","매출지원","리베이트","타서비스","타서비스 지원"].includes(x)).join(", ")||"-";return ""};
 const [current,setCurrent]=useState<Record<string,string>>({});
 useEffect(()=>{const next:Record<string,string>={};comparisonGroups.forEach(g=>g.items.forEach(i=>next[i]=derive(i)));setCurrent(next)},[selected]);
 const currentTotal=["단말기","관리비","연동비","소모품"].reduce((sum,item)=>sum+moneyValue(current[item]),0);
 const currentTotalLabel=`${Math.round(currentTotal/10000)}만원/3년`;
 const saving=Math.max(0,currentTotal-360000);const savingLabel=`약 ${Math.round(saving/10000)}만원 절감`;
 const c=(item:string)=><textarea aria-label={`${item} 현재 사용`} value={current[item]??""} onChange={e=>setCurrent(v=>({...v,[item]:e.target.value}))}/>;
 const o=(item:string)=><textarea className="osstem-cell" aria-label={`${item} 오스템`} defaultValue={osstemDefaults[item]}/>;
 const n=(item:string)=><textarea aria-label={`${item} 비고`} defaultValue={comparisonNotes[item]??""}/>;
 return <div className="compare-page page-shell"><style>{`
 .split-compare{margin-top:12px}.split-label{margin:10px 0 6px 38px;color:#e65518;font-weight:900;font-size:20px;line-height:1}.split-wrap{overflow-x:auto;-webkit-overflow-scrolling:touch}.split-table{width:100%;min-width:720px;border-collapse:collapse;table-layout:fixed;border-top:2px solid #666;border-bottom:1px solid #666;background:#fff}.split-table col:nth-child(1){width:19%}.split-table col:nth-child(2){width:31%}.split-table col:nth-child(3){width:31%}.split-table col:nth-child(4){width:19%}.split-table th,.split-table td{border:1px solid #d5d5d5;padding:0;text-align:center;vertical-align:middle}.split-table thead th{background:#ddd;padding:9px 6px;font-size:12px}.split-table tbody th{font-size:12px;font-weight:800;background:#fff;padding:9px 6px}.split-table textarea{display:block;width:100%;min-height:38px;border:0;resize:none;text-align:center;padding:8px 6px;background:#fff;font:inherit;box-sizing:border-box;overflow:hidden}.split-table textarea.osstem-cell{background:#fff1e8;color:#e15318;font-weight:800}.split-table textarea:focus{outline:2px solid rgba(239,91,32,.25);outline-offset:-2px}@media(max-width:600px){.split-label{margin-left:2px;font-size:16px}.split-table{min-width:680px}}
 `}</style><div className="compare-tools"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">기본 비교안 (직접 수정)</option>{targets.map(x=><option key={x.id} value={x.id}>{x.clinicName} · {x.region} · {x.createdAt.slice(5,10)}</option>)}</select><button onClick={()=>window.print()}><Printer size={16}/>비교표 인쇄</button></div><section className="compare-sheet"><div className="compare-sheet-head"><img src="/osstem-wordmark-transparent.png" alt="OSSTEM" style={{marginLeft:"auto"}}/></div><h1>“오스템 VAN서비스와 비교해 드립니다”</h1><p className="compare-subject">{target?<><strong>{target.clinicName}</strong> · {target.region}{target.currentVanDealer&&` · 현재 ${target.currentVanDealer}`}</>:"설문 답변을 기준으로 현재 사용 조건을 수정할 수 있습니다."}</p><div className="compare-frame">
 <div className="split-compare" data-table-count="4">
  <div className="split-label">사용성</div><div className="split-wrap"><table className="split-table"><colgroup><col/><col/><col/><col/></colgroup><thead><tr><th>항목</th><th>현재 사용</th><th>오스템</th><th>비고</th></tr></thead><tbody><tr><th>단말기 이용</th><td>{c("단말기 이용")}</td><td>{o("단말기 이용")}</td><td>{n("단말기 이용")}</td></tr><tr><th>승인 정산</th><td>{c("승인 정산")}</td><td>{o("승인 정산")}</td><td>{n("승인 정산")}</td></tr><tr><th>PMS연동</th><td>{c("PMS연동")}</td><td>{o("PMS연동")}</td><td>{n("PMS연동")}</td></tr></tbody></table></div>
  <div className="split-label">기본비용</div><div className="split-wrap"><table className="split-table"><colgroup><col/><col/><col/><col/></colgroup><tbody><tr><th>단말기</th><td>{c("단말기")}</td><td>{o("단말기")}</td><td>{n("단말기")}</td></tr><tr><th>관리비</th><td>{c("관리비")}</td><td>{o("관리비")}</td><td>{n("관리비")}</td></tr><tr><th>연동비</th><td>{c("연동비")}</td><td>{o("연동비")}</td><td>{n("연동비")}</td></tr><tr><th>소모품</th><td>{c("소모품")}</td><td>{o("소모품")}</td><td>{n("소모품")}</td></tr></tbody></table></div>
  <div className="split-label">사용조건</div><div className="split-wrap"><table className="split-table"><colgroup><col/><col/><col/><col/></colgroup><tbody><tr><th>의무사용</th><td>{c("의무사용")}</td><td>{o("의무사용")}</td><td>{n("의무사용")}</td></tr><tr><th>대응채널</th><td>{c("대응채널")}</td><td>{o("대응채널")}</td><td>{n("대응채널")}</td></tr><tr><th>내방상담</th><td>{c("내방상담")}</td><td>{o("내방상담")}</td><td>{n("내방상담")}</td></tr><tr><th>출장수리</th><td>{c("출장수리")}</td><td>{o("출장수리")}</td><td>{n("출장수리")}</td></tr><tr><th>위약금</th><td>{c("위약금")}</td><td>{o("위약금")}</td><td>{n("위약금")}</td></tr></tbody></table></div>
  <div className="split-label">특별지원</div><div className="split-wrap"><table className="split-table"><colgroup><col/><col/><col/><col/></colgroup><tbody><tr><th>현금지원</th><td>{c("현금지원")}</td><td>{o("현금지원")}</td><td>{n("현금지원")}</td></tr><tr><th>타서비스</th><td>{c("타서비스")}</td><td>{o("타서비스")}</td><td>{n("타서비스")}</td></tr></tbody></table></div>
 </div>
 <section className="compare-bts"><div className="compare-bts-head"><div><div className="compare-bts-title"><b>BTS</b><h2>핵심 전환 제안</h2></div><p>익숙한 사용 방식을 그대로, 비용과 계약 위험은 더 가볍게</p></div><div className="compare-bts-script">더 합리적인 선택,<br/>오스템 VAN 서비스</div></div>
 <div className="compare-bts-grid">
  <article className="compare-bts-card"><h3>사용성</h3><p>동일한 사용 환경, 더 편리한 서비스</p><div className="compare-bts-flow"><div className="compare-bts-before">기존 업무<br/>단말기(유선)<br/>멀티패드<br/>일상 업무</div><div className="compare-bts-arrow">→</div><div className="compare-bts-after">기존과 동일함<br/>동일하게 제공<br/>(PMS 무관)</div></div></article>
  <article className="compare-bts-card"><h3>운영비용</h3><p>같은 서비스, 더 합리적인 비용</p><div className="compare-bts-flow"><div className="compare-bts-before">{currentTotalLabel}<br/>(현재 사용)</div><div className="compare-bts-arrow">→</div><div className="compare-bts-after">36만원/3년<br/>(오스템)</div></div><div className="compare-bts-saving">{savingLabel}</div></article>
  <article className="compare-bts-card"><h3>사용조건</h3><p>불필요한 부담은 줄이고, 안정적인 운영</p><div className="compare-bts-flow"><div className="compare-bts-before">기기값 2~3배<br/>(위약금 부담)</div><div className="compare-bts-arrow">→</div><div className="compare-bts-after">관리·안전<br/>명확한 조건<br/>3년(동일)<br/>할부 잔금</div></div></article>
  <article className="compare-bts-card"><h3>지원</h3><p>언제든, 더 가까이 도와드리는 지원 체계</p><div className="compare-bts-flow"><div className="compare-bts-before">현금 등<br/>불법지원</div><div className="compare-bts-arrow">→</div><div className="compare-bts-after">운영비용만으로 저렴<br/>+ 오스템 풀플랫폼<br/>서비스 경험</div></div></article>
 </div>
 <div className="compare-bts-band"><strong>운영비용만으로도 저렴<small>+ 오스템 풀서비스 경험</small></strong><span>{savingLabel}</span></div>
 <div className="compare-bts-mentors">
  <article className="compare-bts-mentor"><div className="compare-bts-mentor-head"><span className="compare-bts-num">1</span><h3>변경 부담 최소</h3></div><p>기존 결제 경험은 그대로, 추가 학습 없이 쉽게 전환</p><div className="compare-bts-note"><b>권장 멘트</b><br/>“새로운 결제방식을 배우는 것이 아니라, 단말기 교체로 기존 흐름을 유지하면서 오스템 편의를 더하는 제안입니다.”</div></article>
  <article className="compare-bts-mentor"><div className="compare-bts-mentor-head"><span className="compare-bts-num">2</span><h3>PMS 연동 편의</h3></div><p>수납·정산 수정일을 줄여 업무 효율을 높입니다.</p><div className="compare-bts-note"><b>권장 멘트</b><br/>“직원이 금액을 다시 입력하고 나중에 정산을 맞추는 번거로움을 줄이는 것이 핵심입니다.”</div></article>
  <article className="compare-bts-mentor"><div className="compare-bts-mentor-head"><span className="compare-bts-num">3</span><h3>현장 밀착 지원</h3></div><p>오스템 전국 영업망과 전담 인력이 직접 함께합니다.</p><div className="compare-bts-note"><b>권장 멘트</b><br/>“결제만 파는 서비스가 아니라, 오스템 담당자가 방문해 함께 챙기는 운영관리 서비스입니다.”</div></article>
 </div></section>
 </div></section></div>
}

const riskyTerms=new Set(["현금지원","무료기기","월비용면제","매출지원","리베이트","타서비스 지원"]);
function monthKey(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function monthDiff(ym:string,base:Date){const m=/^(\d{4})-(\d{2})/.exec(ym||"");if(!m)return 999;return (Number(m[1])-base.getFullYear())*12+(Number(m[2])-(base.getMonth()+1))}

function Dashboard({summary,max,refresh}:{summary:Summary;max:number;refresh:()=>Promise<void>}){
 const [rep,setRep]=useState("");
 const targets=rep?summary.targets.filter(x=>x.salesRep===rep):summary.targets;
 const rows=[...targets].sort((a,b)=>(a.contractEndDate||"9999").localeCompare(b.contractEndDate||"9999"));
 const now=new Date();const thisMonth=monthKey(now);
 const thisMonthCount=targets.filter(x=>(x.createdAt||"").slice(0,7)===thisMonth).length;
 const expiry={m3:0,m6:0,m12:0};targets.forEach(x=>{const d=monthDiff(x.contractEndDate,now);if(d>=0&&d<=3)expiry.m3++;else if(d>3&&d<=6)expiry.m6++;else if(d>6&&d<=12)expiry.m12++});
 const immediateCount=targets.filter(x=>(x.contactWhen||"").includes("즉시")||(x.deliveryMethod||"").includes("즉시")).length;
 const complianceCount=targets.filter(x=>(x.contractTerms||[]).some(t=>riskyTerms.has(t))).length;
 const regionMap=new Map<string,number>();targets.forEach(x=>regionMap.set(x.region,(regionMap.get(x.region)||0)+1));const regions=[...regionMap.entries()].map(([region,count])=>({region,count})).sort((a,b)=>b.count-a.count);const regionMax=Math.max(1,...regions.map(x=>x.count));
 const monthCounts=new Map<string,number>();for(let i=0;i<6;i++){const d=new Date(now.getFullYear(),now.getMonth()+i,1);monthCounts.set(monthKey(d),0)}targets.forEach(x=>{const k=(x.contractEndDate||"").slice(0,7);if(monthCounts.has(k))monthCounts.set(k,(monthCounts.get(k)||0)+1)});const expiryMonths=[...monthCounts.entries()].map(([month,count])=>({month,count}));
 const painMap=new Map<string,number>();targets.forEach(x=>[...(x.inconveniences||[]),...(x.improvementItems||[])].forEach(p=>painMap.set(p,(painMap.get(p)||0)+1)));const pains=[...painMap.entries()].map(([pain,count])=>({pain,count})).sort((a,b)=>b.count-a.count).slice(0,6);
 const csv=()=>{const head=["치과명","지역","시군구","만료연월","현재 VAN","월 비용","전달 방식","담당","조사일"];const data=rows.map(x=>[x.clinicName,x.region,x.district,x.contractEndDate,x.currentVanDealer,x.monthlyCost,x.deliveryMethod,x.salesRep,x.createdAt.slice(0,10)]);const blob=new Blob(["\ufeff"+[head,...data].map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="VAN_상담대상.csv";a.click();URL.revokeObjectURL(a.href)};
 return <div className="dashboard page-shell"><div className="dashboard-head"><div><span className="eyebrow">SURVEY DASHBOARD</span><h1>본사 현황</h1><p>설문 실적과 약정 만료 영업기회를 한 화면에서 확인합니다.</p></div><button onClick={()=>void refresh()}><RefreshCw size={16}/>새로고침</button></div><div className="dash-tools"><select value={rep} onChange={e=>setRep(e.target.value)}><option value="">전체 영업사원</option>{summary.reps.map(x=><option key={x}>{x}</option>)}</select><button onClick={csv}><Download size={16}/>엑셀 내려받기</button></div><div className="kpis five"><Kpi label="총 조사" value={targets.length} unit="건"/><Kpi label="이번 달 조사" value={thisMonthCount} unit="건"/><Kpi label="3개월 내 만료" value={expiry.m3} unit="곳" alert/><Kpi label="즉시 비교안 희망" value={immediateCount} unit="곳" alert/><Kpi label="준법 확인 필요" value={complianceCount} unit="건"/></div><div className="chart-grid"><section className="chart-card"><h2><MapPin size={20}/>지역별 조사 현황</h2>{regions.length?<RegionalMapChart regions={regions} max={regionMax}/>:<Empty/>}</section><section className="chart-card"><h2>약정 만료 파이프라인 <small>향후 6개월</small></h2><div className="month-chart">{expiryMonths.map(x=>{const top=Math.max(1,...expiryMonths.map(v=>v.count));return <div key={x.month}><b>{x.count}</b><i style={{height:`${Math.max(5,x.count/top*100)}%`}}/><span>{Number(x.month.slice(5))}월</span></div>})}</div><div className="pipeline mini"><Kpi label="3개월 이내" value={expiry.m3} unit="건"/><Kpi label="3~6개월" value={expiry.m6} unit="건"/><Kpi label="6~12개월" value={expiry.m12} unit="건"/></div></section></div><div className="chart-grid lower"><section className="chart-card"><h2>불편 · 개선 요구 TOP</h2>{pains.length?pains.map((x,i)=><div className="rank-row" key={x.pain}><span><b>{i+1}</b>{x.pain}</span><strong>{x.count}<small>건</small></strong></div>):<Empty/>}</section><section className="chart-card target-card"><h2>공략 리스트 <small>만료 임박순</small></h2>{rows.length?<div className="table-wrap"><table><thead><tr><th>치과 / 지역</th><th>만료</th><th>현재 VAN</th><th>월 비용</th><th>희망 방식</th><th>담당</th><th>조사일</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.clinicName}</strong><small>{x.region} {x.district}</small></td><td><span className="pill">{x.contractEndDate||"미확인"}</span></td><td>{x.currentVanDealer||"-"}</td><td>{x.monthlyCost||"-"}</td><td>{x.deliveryMethod||"-"}</td><td>{x.salesRep||"-"}</td><td>{x.createdAt.slice(5,10)}</td></tr>)}</tbody></table></div>:<Empty/>}</section></div></div>
}
function Kpi({label,value,unit,alert}:{label:string;value:number|string;unit:string;alert?:boolean}){return <article className={alert?"alert-kpi":""}><small>{alert&&<ShieldAlert size={15}/>} {label}</small><strong>{value}<em>{unit}</em></strong></article>}
function Empty(){return <div className="empty">설문이 제출되면 집계 결과가 표시됩니다.</div>}