import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const surveys = sqliteTable("surveys", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  clinicName: text("clinic_name").notNull(),
  region: text("region").notNull(),
  district: text("district").notNull(),
  respondentRole: text("respondent_role").notNull().default(""),
  devices: text("devices").notNull(),
  terminalCount: integer("terminal_count").notNull().default(0),
  vanCompany: text("van_company").notNull().default(""),
  pmsIntegrated: text("pms_integrated").notNull(),
  monthlyFee: text("monthly_fee").notNull(),
  freeSupplies: text("free_supplies").notNull(),
  satisfaction: integer("satisfaction").notNull(),
  replacementIntent: text("replacement_intent").notNull(),
  longContract: text("long_contract").notNull(),
  notes: text("notes").notNull().default(""),
  linkedServices: text("linked_services").notNull().default("[]"),
  inconveniences: text("inconveniences").notNull().default("[]"),
  contractType: text("contract_type").notNull().default(""),
  costItems: text("cost_items").notNull().default("[]"),
  contractTerms: text("contract_terms").notNull().default("[]"),
  improvementItems: text("improvement_items").notNull().default("[]"),
  salesRep: text("sales_rep").notNull().default(""),
  terminalUsePeriod: text("terminal_use_period").notNull().default(""),
  contractEndDate: text("contract_end_date").notNull().default(""),
  monthlyCost: text("monthly_cost").notNull().default(""),
  currentPms: text("current_pms").notNull().default(""),
  currentVanDealer: text("current_van_dealer").notNull().default(""),
  contact: text("contact").notNull().default(""),
  contactWhen: text("contact_when").notNull().default(""),
  linkFee: text("link_fee").notNull().default(""),
  deliveryMethod: text("delivery_method").notNull().default(""),
  fieldMemo: text("field_memo").notNull().default(""),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
